// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_YoSyZ_J0ZBNXhgMDgEdvz6QCagtZawo',
    appId: '1:335712541238:web:09547eccc76a5d6e1d9697',
    messagingSenderId: '335712541238',
    projectId: 'authentication-26f5c',
    authDomain: 'authentication-26f5c.firebaseapp.com',
    storageBucket: 'authentication-26f5c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaCs6JXObnT0WfSiMdLEzTl60OnGWW4-c',
    appId: '1:335712541238:android:35fb85feeeeb7ec71d9697',
    messagingSenderId: '335712541238',
    projectId: 'authentication-26f5c',
    storageBucket: 'authentication-26f5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCplsORPGCwJl6wggSb4Ot0-yk3BXlxSRM',
    appId: '1:335712541238:ios:03cb41f47ef1e0cf1d9697',
    messagingSenderId: '335712541238',
    projectId: 'authentication-26f5c',
    storageBucket: 'authentication-26f5c.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCplsORPGCwJl6wggSb4Ot0-yk3BXlxSRM',
    appId: '1:335712541238:ios:03cb41f47ef1e0cf1d9697',
    messagingSenderId: '335712541238',
    projectId: 'authentication-26f5c',
    storageBucket: 'authentication-26f5c.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_YoSyZ_J0ZBNXhgMDgEdvz6QCagtZawo',
    appId: '1:335712541238:web:bb81adb52e1d6ff31d9697',
    messagingSenderId: '335712541238',
    projectId: 'authentication-26f5c',
    authDomain: 'authentication-26f5c.firebaseapp.com',
    storageBucket: 'authentication-26f5c.appspot.com',
  );

}